from datetime import datetime
from typing import Optional, Any, Dict
from pydantic import BaseModel, Field

class TransactionBase(BaseModel):
    """
    Base Pydantic model for a decoded Solana transaction.
    Mirrors the DecodedSolanaTransaction SQLAlchemy model.
    """
    transaction_signature: str = Field(..., description="Unique signature of the Solana transaction.")
    block_slot: int = Field(..., description="The block number where the transaction occurred.")
    block_time: datetime = Field(..., description="Timestamp of the block when the transaction occurred (UTC).")
    program_id: str = Field(..., description="The main program ID involved in the transaction.")
    event_type: str = Field(..., description="Categorized type of the event (e.g., 'SPL Token Transfer', 'Compute Budget').")
    token_mint_address_in: Optional[str] = Field(None, description="Mint address of the token received/bought.")
    amount_in: Optional[float] = Field(None, description="Amount of token received/bought.")
    token_mint_address_out: Optional[str] = Field(None, description="Mint address of the token sent/sold.")
    amount_out: Optional[float] = Field(None, description="Amount of token sent/sold.")
    signer_address: Optional[str] = Field(None, description="Wallet address that initiated the transaction.")
    raw_log_message: Dict[str, Any] = Field(..., description="The full original raw JSON log message from Kafka.")
    created_at: datetime = Field(..., description="Timestamp when the record was inserted into the database (UTC).")

    class Config:
        from_attributes = True # Use from_attributes for Pydantic v2 instead of orm_mode
        json_schema_extra = {
            "example": {
                "transaction_signature": "5pW5jSzSM9iRA8azgEgLJ4dXkPtBS7jEcfK81hDxhe",
                "block_slot": 123456789,
                "block_time": "2026-02-11T12:00:00Z",
                "program_id": "TokenkegQfe",
                "event_type": "SPL Token Transfer",
                "token_mint_address_in": "So11111111111111111111111111111111111111112",
                "amount_in": 1.5,
                "token_mint_address_out": "EPjFWdd5AufqSSqeM2qN1xzybapT8Ga6WgKtEke9NAtg",
                "amount_out": 1000.0,
                "signer_address": "8pW5jSzSM9iRA8azgEgLJ4dXkPtBS7j",
                "raw_log_message": {"jsonrpc":"2.0", "method":"logsNotification", "params":{}},
                "created_at": "2026-02-11T12:05:00Z"
            }
        }

class TransactionResponse(TransactionBase):
    """
    Pydantic model for a decoded Solana transaction returned by the API.
    Includes the 'id' field which is generated by the database.
    """
    id: int = Field(..., description="Database ID of the record.")

class AggregationResult(BaseModel):
    """
    Pydantic model for aggregation results (e.g., counts by program_id or event_type).
    """
    name: str = Field(..., description="Name of the aggregated item (e.g., program ID, event type).")
    count: int = Field(..., description="Count of transactions for this item.")

    class Config:
        json_schema_extra = {
            "example": {
                "name": "SPL Token Event",
                "count": 1234
            }
        }
